import React, { useState, useEffect } from 'react';
import { Send, Copy, RefreshCw, Sparkles, Edit3, Check } from 'lucide-react';
import { motion } from 'framer-motion';

export default function DraftOutreach({ apiHost }) {
  const [actionCards, setActionCards] = useState([]);
  const [editingId, setEditingId] = useState(null);
  const [editText, setEditText] = useState('');
  const [copiedId, setCopiedId] = useState(null);
  const [loading, setLoading] = useState(false);

  const fetchDrafts = async () => {
    try {
      const res = await fetch(`${apiHost}/recruiter/queue`);
      const data = await res.json();
      setActionCards(data.action_cards || []);
    } catch (e) {
      console.error("Failed to load queue drafts:", e);
    }
  };

  useEffect(() => {
    fetchDrafts();
    const interval = setInterval(fetchDrafts, 5000);
    return () => clearInterval(interval);
  }, []);

  const handleEdit = (card) => {
    setEditingId(card.id);
    setEditText(card.outreach_draft);
  };

  const handleSaveEdit = async (id) => {
    try {
      const res = await fetch(`${apiHost}/recruiter/action`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          action_card_id: id,
          decision: 'Edited',
          notes: 'Outreach draft updated by recruiter',
          edits: editText
        })
      });
      const data = await res.json();
      if (data.status === 'success') {
        fetchDrafts();
        setEditingId(null);
      }
    } catch (e) {
      console.error("Failed to save draft edits:", e);
    }
  };

  const handleApprove = async (id, draftText) => {
    try {
      const res = await fetch(`${apiHost}/recruiter/action`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          action_card_id: id,
          decision: 'Approved',
          notes: 'Outreach draft approved',
          edits: draftText
        })
      });
      const data = await res.json();
      if (data.status === 'success') {
        fetchDrafts();
      }
    } catch (e) {
      console.error("Failed to approve draft:", e);
    }
  };

  const handleCopy = (id, text) => {
    navigator.clipboard.writeText(text);
    setCopiedId(id);
    setTimeout(() => setCopiedId(null), 2000);
  };

  const handleRegenerateAll = async () => {
    setLoading(true);
    // Trigger standard fetch refresh
    await fetchDrafts();
    setTimeout(() => setLoading(false), 800);
  };

  // We filter to show candidates with drafts. Usually all recommended candidates have one.
  const pendingCards = actionCards.filter(c => c.status === 'Pending');
  const approvedCards = actionCards.filter(c => c.status === 'Approved' || c.status === 'Edited');

  return (
    <div className="outreach-page">
      <div className="outreach-header glass-panel">
        <div>
          <h3 style={{ color: 'var(--text-main)', display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
            <Sparkles size={20} color="var(--brand-primary)" /> AI-Generated Outreach Drafts
          </h3>
          <p style={{ fontSize: '0.85rem', color: 'var(--text-muted)', marginTop: '0.25rem' }}>
            Review, edit, and approve personalized messages generated by the Recommendation Agent.
          </p>
        </div>
        <button className="btn btn-edit" style={{ flex: 'none', padding: '0.5rem 1rem' }} onClick={handleRegenerateAll} disabled={loading}>
          <RefreshCw size={14} className={loading ? "spin" : ""} /> {loading ? "Refreshing..." : "Sync Queue"}
        </button>
      </div>

      <div className="cards-container" style={{ marginTop: '1rem' }}>
        {pendingCards.map((card, idx) => (
          <motion.div
            key={card.id}
            className="glass-panel action-card"
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: idx * 0.1 }}
          >
            <div className="card-header">
              <div>
                <h3 className="candidate-name">{card.candidate_name}</h3>
                <p style={{ fontSize: '0.8rem', color: 'var(--text-muted)' }}>
                  Job ID: <span style={{ color: 'var(--brand-info)' }}>{card.job_id}</span> · Confidence Score: <span style={{ color: 'var(--brand-purple)', fontWeight: 600 }}>{card.confidence_score || card.match_score}%</span>
                </p>
              </div>
              <div className="match-circle" style={{ width: '48px', height: '48px', fontSize: '0.9rem' }}>
                {card.match_score}%
              </div>
            </div>

            {editingId === card.id ? (
              <div>
                <textarea
                  className="textarea-jd"
                  style={{ height: '200px', marginTop: '0.5rem' }}
                  value={editText}
                  onChange={(e) => setEditText(e.target.value)}
                />
                <div style={{ display: 'flex', gap: '0.5rem', marginTop: '0.5rem' }}>
                  <button className="btn btn-approve" style={{ flex: 'none', padding: '0.5rem 1rem', fontSize: '0.8rem' }} onClick={() => handleSaveEdit(card.id)}>
                    <Check size={14} /> Save Changes
                  </button>
                  <button className="btn btn-edit" style={{ flex: 'none', padding: '0.5rem 1rem', fontSize: '0.8rem' }} onClick={() => setEditingId(null)}>
                    Cancel
                  </button>
                </div>
              </div>
            ) : (
              <div className="outreach-draft-box">
                <pre className="outreach-draft-text">{card.outreach_draft}</pre>
              </div>
            )}

            <div className="actions-bar" style={{ marginTop: '0.75rem' }}>
              <button className="btn btn-approve" onClick={() => handleApprove(card.id, card.outreach_draft)}>
                <Send size={16} /> Approve & Send
              </button>
              <button className="btn btn-edit" onClick={() => handleEdit(card)}>
                <Edit3 size={16} /> Edit Draft
              </button>
              <button className="btn btn-edit" style={{ flex: 'none', padding: '0.5rem' }} onClick={() => handleCopy(card.id, card.outreach_draft)}>
                {copiedId === card.id ? <Check size={16} color="var(--brand-success)" /> : <Copy size={16} />}
              </button>
            </div>
          </motion.div>
        ))}

        {approvedCards.map((card, idx) => (
          <motion.div
            key={card.id}
            className="glass-panel action-card"
            style={{ opacity: 0.8 }}
            initial={{ opacity: 0 }}
            animate={{ opacity: 0.8 }}
          >
            <div className="card-header">
              <div>
                <h3 className="candidate-name" style={{ color: 'var(--text-muted)' }}>{card.candidate_name}</h3>
                <p style={{ fontSize: '0.8rem', color: 'var(--text-muted)' }}>
                  Job ID: {card.job_id} · Outreach Approved & Sent
                </p>
              </div>
              <span className="status-pill submitted" style={{ alignSelf: 'center' }}>✓ Approved</span>
            </div>
            <div className="outreach-draft-box" style={{ background: 'rgba(15,23,42,0.01)', borderStyle: 'dashed' }}>
              <pre className="outreach-draft-text" style={{ color: 'var(--text-muted)' }}>{card.outreach_draft}</pre>
            </div>
          </motion.div>
        ))}

        {pendingCards.length === 0 && approvedCards.length === 0 && (
          <div className="glass-panel" style={{ padding: '3rem', textAlign: 'center', color: 'var(--text-muted)' }}>
            No recommendations in active session. Run matching in the Priority Queue first to generate candidate outreach drafts.
          </div>
        )}
      </div>
    </div>
  );
}
